
server.port=8080

# Spring
spring.application.name=global-buddy-backend

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bridgeu?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


dashscope.api.key=sk-85ccccefc7ce41b088c9694e900392af

logging.level.com.globalbuddy=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

spring.main.allow-bean-definition-overriding=true

# - Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zhiyipan22@gmail.com
spring.mail.password=frls pkew fxsf pzqn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


app.email.enabled=true
app.sms.enabled=false